### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by mbaluda** [nodesecurity/nsp#165]
node_modules/nsp/bin/nsp check --warn-only --output checkstyle --offline --advisoriesPath=advisories.json
/[...]/node_modules/nsp/lib/check.js:31
    if (versionRE.test(match[0])) {
                            ^

TypeError: Cannot read property '0' of null
    at Object.internals.findLines (/[...]/node_modules/nsp/lib/check.js:31:29)
    at /[...]/node_modules/nsp/lib/check.js:207:30
    at Object.getShrinkwrapDependencies (/[...]/node_modules/nsp/node_modules/nodesecurity-npm-utils/index.js:30:10)
    at module.exports (/[...]/node_modules/nsp/lib/check.js:178:14)
    at Object.onCommand [as command] (/[...]/node_modules/nsp/lib/commands/check.js:22:3)
    at doCb (/[...]/node_modules/nsp/node_modules/subcommand/index.js:39:19)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)

**Comment by evilpacket** [comment]
The only formatter that currently works with the offline mode is `codeclimate` - this should change with the rewrite of the client that is in progress.
