### ISSUE TITLE
Failed to install with nodejs v8 and npm v5

### ISSUE THREAD

**Issue by stoshiya** [nodesecurity/nsp#167]
```sh
$ node -v
v8.0.0
$ npm -v
5.0.1
$ npm install -g nsp
npm ERR! Path must be a string. Received undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/toshiya/.npm/_logs/2017-06-01T04_45_54_075Z-debug.log
$ cat ~/.npm/_logs/2017-06-01T04_45_54_075Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/toshiya/.nodebrew/node/v8.0.0/bin/node',
1 verbose cli   '/Users/toshiya/.nodebrew/current/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'nsp' ]
2 info using npm@5.0.1
3 info using node@v8.0.0
4 silly install loadCurrentTree
5 silly install readGlobalPackageData
6 http fetch GET 200 https://registry.npmjs.org/nsp 26ms (from cache)
7 silly pacote tag manifest for nsp@latest fetched in 58ms
8 verbose stack TypeError: Path must be a string. Received undefined
8 verbose stack     at assertPath (path.js:28:11)
8 verbose stack     at Object.relative (path.js:1248:5)
8 verbose stack     at computeVersionSpec (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/lib/install/deps.js:282:27)
8 verbose stack     at Installer.normalizeCurrentTree (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/lib/install.js:370:69)
8 verbose stack     at Array.<anonymous> (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
8 verbose stack     at LOOP (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
8 verbose stack     at /Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
8 verbose stack     at /Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/lib/install.js:619:16
8 verbose stack     at /Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/iferr/index.js:13:50
8 verbose stack     at thenHandleErrors (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:233:5)
8 verbose stack     at f (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
8 verbose stack     at handleComplete (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
8 verbose stack     at f (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
8 verbose stack     at handleComplete (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
8 verbose stack     at f (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/once/once.js:25:25)
8 verbose stack     at handleComplete (/Users/toshiya/.nodebrew/node/v8.0.0/lib/node_modules/npm/node_modules/read-package-tree/rpt.js:22:28)
9 verbose cwd /Users/toshiya/work/express-fluent-logger
10 verbose Darwin 16.6.0
11 verbose argv "/Users/toshiya/.nodebrew/node/v8.0.0/bin/node" "/Users/toshiya/.nodebrew/current/bin/npm" "install" "-g" "nsp"
12 verbose node v8.0.0
13 verbose npm  v5.0.1
14 error Path must be a string. Received undefined
15 verbose exit [ 1, true ]
```

**Comment by evilpacket** [comment]
I just tried with the following configuration. Not sure what failed for that particular version but it would be good to go with the latest anyway.
node: v8.2.1
npm: 5.3.0

```
npm i nsp -g
+ nsp@2.6.3
added 40 packages in 6.702s
```

```
nsp (master)$ nsp check
(+) No known vulnerabilities found
```
