### ISSUE TITLE
nsp default output formatter fails if process.stdout.getWindowSize()[0] <= 7

### ISSUE THREAD

**Issue by tdewitt** [nodesecurity/nsp#174]
nsp default output formatter fails if `process.stdout.isTTY == true` and `process.stdout.getWindowSize <= 7`.  When using buildkite, the following conditions are true:

```
process.stdout.isTTY == true
process.stdout.getWindowSize()[0] == 0
```

In this case, if nsp finds any vulnerabilities, it throws an exception:
```
$ nsp check
/home/tucker/.nvm/versions/node/v4.8.0/lib/node_modules/nsp/node_modules/cli-table/lib/utils.js:12
  return Array(times + 1).join(str);
         ^

RangeError: Invalid array length
    at exports.repeat (/home/tucker/.nvm/versions/node/v4.8.0/lib/node_modules/nsp/node_modules/cli-table/lib/utils.js:12:10)
    at line (/home/tucker/.nvm/versions/node/v4.8.0/lib/node_modules/nsp/node_modules/cli-table/lib/index.js:140:11)
    at lineTop (/home/tucker/.nvm/versions/node/v4.8.0/lib/node_modules/nsp/node_modules/cli-table/lib/index.js:154:13)
    at Table.toString (/home/tucker/.nvm/versions/node/v4.8.0/lib/node_modules/nsp/node_modules/cli-table/lib/index.js:252:5)
    at /home/tucker/.nvm/versions/node/v4.8.0/lib/node_modules/nsp/lib/formatters/default.js:49:27
    at Array.forEach (native)
    at Object.module.exports [as output] (/home/tucker/.nvm/versions/node/v4.8.0/lib/node_modules/nsp/lib/formatters/default.js:34:6)
    at /home/tucker/.nvm/versions/node/v4.8.0/lib/node_modules/nsp/lib/commands/check.js:25:23
    at /home/tucker/.nvm/versions/node/v4.8.0/lib/node_modules/nsp/lib/check.js:240:7
    at /home/tucker/.nvm/versions/node/v4.8.0/lib/node_modules/nsp/node_modules/wreck/lib/index.js:472:20
```

**Comment by tdewitt** [comment]
I can't get the tests to run successfully and since I'm not at all a JS developer, I'd hate to spend time on this only to realize I botched it but I _think_ this would work:

```
$ git diff
diff --git a/lib/formatters/default.js b/lib/formatters/default.js
index c2fafd4..53aaf61 100644
--- a/lib/formatters/default.js
+++ b/lib/formatters/default.js
@@ -18,7 +18,9 @@ module.exports = function (err, data, pkgPath) {
 
   var width = 80;
   if (process.stdout.isTTY) {
-    width = process.stdout.getWindowSize()[0] - 10;
+    if (process.stdout.getWindowSize()[0] > 90) {
+      width = process.stdout.getWindowSize()[0] - 10;
+    }
   }
   if (data.length === 0) {
```

That would enforce a minimum output width of 80 chars and expand for any displays wider than that.  Since the current default is 80 chars for times where isTTY is false, it's seems sane to stick with that as the bare minimum.
