### ISSUE TITLE
Exception when using codeclimate output

### ISSUE THREAD

**Issue by thom-nic** [nodesecurity/nsp#186]
`nsp check` throws an unexpected exception when using the coedclimate reporter.  Works fine with the default reporter (it should report 8 issues.)  Please let me know what other information I can provide.
```
± nsp check --output codeclimate
/Users/thom/.nvm/versions/node/v6.11.0/lib/node_modules/nsp/lib/formatters/codeclimate.js:27
          begin: data[i].line.start,
                             ^

TypeError: Cannot read property 'start' of undefined
    at Object.module.exports [as output] (/Users/thom/.nvm/versions/node/v6.11.0/lib/node_modules/nsp/lib/formatters/codeclimate.js:27:30)
    at /Users/thom/.nvm/versions/node/v6.11.0/lib/node_modules/nsp/lib/commands/check.js:24:23
    at /Users/thom/.nvm/versions/node/v6.11.0/lib/node_modules/nsp/lib/check.js:240:7
    at /Users/thom/.nvm/versions/node/v6.11.0/lib/node_modules/nsp/node_modules/wreck/lib/index.js:472:20
    at finish (/Users/thom/.nvm/versions/node/v6.11.0/lib/node_modules/nsp/node_modules/wreck/lib/index.js:326:16)
    at wrapped (/Users/thom/.nvm/versions/node/v6.11.0/lib/node_modules/nsp/node_modules/wreck/node_modules/hoek/lib/index.js:866:20)
    at onReaderFinish (/Users/thom/.nvm/versions/node/v6.11.0/lib/node_modules/nsp/node_modules/wreck/lib/index.js:363:16)
    at g (events.js:292:16)
    at emitNone (events.js:91:20)
    at emit (events.js:185:7)

 ± nsp --version
2.7.0
```

**Comment by thom-nic** [comment]
Just noticed the 2.8.0 release so I installed it and retried - same error.

**Comment by evilpacket** [comment]
The codeclimate formatter only works with the `--offline` mode as our api doesn't return the line start and end markers. The client is currently going through a re-write so we can probably do something about an error message if you're trying to use a formatter that requires this mode.
