### ISSUE TITLE
Old versions stopped working

### ISSUE THREAD

**Issue by xicombd** [nodesecurity/nsp#41]
Hey!

It looks like old versions of the `nsp` cli stopped working over the weekend.

I've updated to `v2.0.0` and it's working fine but would it be possible for you to keep the old client working?

Here's the error I got:
```
/Users/franciscod/.nvm/versions/node/v4.2.1/lib/node_modules/nsp/node_modules/text-table/index.js:59
    return m ? m.index + 1 : c.length;
                              ^

TypeError: Cannot read property 'length' of undefined
    at dotindex (/Users/franciscod/.nvm/versions/node/v4.2.1/lib/node_modules/nsp/node_modules/text-table/index.js:59:31)
    at /Users/franciscod/.nvm/versions/node/v4.2.1/lib/node_modules/nsp/node_modules/text-table/index.js:11:21
    at Array.forEach (native)
    at forEach (/Users/franciscod/.nvm/versions/node/v4.2.1/lib/node_modules/nsp/node_modules/text-table/index.js:73:31)
    at /Users/franciscod/.nvm/versions/node/v4.2.1/lib/node_modules/nsp/node_modules/text-table/index.js:10:9
    at Array.reduce (native)
    at reduce (/Users/franciscod/.nvm/versions/node/v4.2.1/lib/node_modules/nsp/node_modules/text-table/index.js:63:30)
    at module.exports (/Users/franciscod/.nvm/versions/node/v4.2.1/lib/node_modules/nsp/node_modules/text-table/index.js:9:20)
    at prettyOutput (/Users/franciscod/.nvm/versions/node/v4.2.1/lib/node_modules/nsp/lib/prettyOutput.js:32:17)
    at /Users/franciscod/.nvm/versions/node/v4.2.1/lib/node_modules/nsp/commands/auditPackage/index.js:35:9
```

Cheers!

**Comment by olivierba** [comment]
same issue here

**Comment by evilpacket** [comment]
The old client will not continue to work and should be you should upgrade to v2.0.0 or greater. Even if were working It would not get the number of new advisories that have recently been published as the format has changed. Also, the old client does not produce accurate results, potentially missing known vulnerabilities. It's a nasty bug in the old client when it doesn't get a response from the server it fails with no vulnerabilities found. Because of this many people would not notice there is a new client or upgrade so we had to purposely find a bug and crash the old client so that you would notice the old client isn't working and has an upgrade available. 

It's certainly not the cleanest way we could have done this but at this point the path forward is to upgrade.

**Comment by dscape** [comment]
:+1: 

Excellent work @evilpacket, happy to see so much attention being put in this essential project for node!
