### ISSUE TITLE
Don't require package.json if I specify shrinkwrap

### ISSUE THREAD

**Issue by pdehaan** [nodesecurity/nsp#50]
I'm using the **gulp-nsp** module below, but I think this is more of a core **nsp** issue.
I'm specifying a `shrinkwrap` object below via _npm-shrinkwrap.json_, but it gives me an error if I don't also specify the `package` object. It turns out, it only needs a `name` property in the `package` object, which it could easily get from the shrinkwrap file. I think if `shrinkwrap` is specified, then `package` should be optional.

```sh
var gulp = require('gulp');
var gulpNSP = require('gulp-nsp');

var shrinkwrap = require('./npm-shrinkwrap.json');

// To check your project
gulp.task('nsp', function (done) {
  gulpNSP({
    // output: 'summary',
    // package: require('./package.json'),
    // package: {name: shrinkwrap.name},
    shrinkwrap: shrinkwrap
  }, done);
});
```

Output:
```sh
$ gulp nsp

[19:52:30] Using gulpfile ~/dev/gulp-nsp-test/gulpfile.js
[19:52:30] Starting 'nsp'...
[19:52:30] 'nsp' errored after 3.99 ms
[19:52:30] TypeError: Cannot read property 'length' of undefined
    at /Users/pdehaan/dev/gulp-nsp-test/node_modules/gulp-nsp/index.js:27:45
    at Object.module.exports [as check] (/Users/pdehaan/dev/gulp-nsp-test/node_modules/gulp-nsp/node_modules/nsp/lib/check.js:202:14)
    at rsGulp (/Users/pdehaan/dev/gulp-nsp-test/node_modules/gulp-nsp/index.js:23:7)
    at Gulp.<anonymous> (/Users/pdehaan/dev/gulp-nsp-test/gulpfile.js:8:3)
    at module.exports (/Users/pdehaan/dev/gulp-nsp-test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/pdehaan/dev/gulp-nsp-test/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/pdehaan/dev/gulp-nsp-test/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/pdehaan/dev/gulp-nsp-test/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/pdehaan/.npm-packages/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
```

**Comment by nlf** [comment]
i agree, i'll work on getting this requirement lifted

**Comment by nlf** [comment]
@pdehaan this is live now, package shouldn't be required any more. it's possible we'll require it in the future, but for now we weren't actually using it for anything when the shrinkwrap was supplied, so we lifted it.

**Comment by chasevida** [comment]
Hi, sorry if this is a dumb question but seems sorta related. Just want to clarify, if there is a `npm-shrinkwrap.json` file it will check against that and not the `package.json` file?

**Comment by nlf** [comment]
not really. this issue contains old information. how it works is this -

if you provide only a package.json, we resolve that with the latest matching semver of each module that's currently installable. and check those.

if you provide both package.json and npm-shrinkwrap.json, we do the same resolution, but instead of using the latest matching semver of every module, we try to find the module in the shrinkwrap and use the version noted there instead.

**Comment by chasevida** [comment]
Thanks @nlf, much appreciated.
